### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'train_docs_all_rels'

### ISSUE THREAD

**Issue by katherine-atwell** [yxuezhang/CTNet#1]
Hello, 

I'm currently trying to run your code and am getting the above error when running ./processed_data/splits_pairs.py. Is there a data file that I'm missing?

Thanks so much!

**Comment by StudentWorker** [comment]
are u solve this problem? i think is the dataset not right.

**Comment by StudentWorker** [comment]
can u share your ldc pdtb2.0 dataset to me .

**Comment by nangying1112** [comment]
Sorry for the late reply. We cannot share PDTB 2.0 because it is not a free dataset and is protected by copyright, but I can provide a script "documents_all_rels.py" that extracts the paragraphs from the dataset. Please see the newest version.

**Comment by StudentWorker** [comment]
As long as it can provide a way to implement it, it may be good.
For example, where to download the doc.
How to execute the preprocessing script.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yingxue ***@***.***&gt;; 
发送时间: 2021年11月15日(星期一) 下午3:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yxuezhang/CTNet] FileNotFoundError: [Errno 2] No such file or directory: &#39;train_docs_all_rels&#39; (#1)





 
Sorry for the late reply. We cannot share PDTB 2.0 because it is not a free dataset and is protected by copyright, but I can provide a script "documents_all_rels.py" that extracts the paragraphs from the dataset.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nangying1112** [comment]
You need to get PDTB 2.0 first in some way, then use this script to extract paragraphs from the dataset. Just put the script "documents_all_rels.py" and the folder “PDTB 2.0” under the same path, then run this script to get "train_docs_all_rels/valid_docs_all_rels/test_docs_all_rels".

**Comment by StudentWorker** [comment]
i think i need some way to get this dataset.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yingxue ***@***.***&gt;; 
发送时间: 2021年11月15日(星期一) 晚上8:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yxuezhang/CTNet] FileNotFoundError: [Errno 2] No such file or directory: &#39;train_docs_all_rels&#39; (#1)





 
You need to get PDTB 2.0 first in some way, then use this script to extract paragraphs from the dataset. Just put the script "documents_all_rels.py" and the folder “PDTB 2.0” under the same path, run this script, then you can get "train_docs_all_rels/valid_docs_all_rels/test_docs_all_rels".
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StudentWorker** [comment]
I have a CSV of ptdb2.0 here, but I don't know what ptdb2.0 looks like. I think if you can provide me with a screenshot, I should be able to solve this problem.


Can send pictures to ***@***.*** 。&nbsp;
Sorry for the inconvenience.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yxuezhang/CTNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 晚上8:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yxuezhang/CTNet] FileNotFoundError: [Errno 2] No such file or directory: 'train_docs_all_rels' (#1)





 
You need to get PDTB 2.0 first in some way, then use this script to extract paragraphs from the dataset. Just put the script "documents_all_rels.py" and the folder “PDTB 2.0” under the same path, run this script, then you can get "train_docs_all_rels/valid_docs_all_rels/test_docs_all_rels".
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by katherine-atwell** [comment]
> You need to get PDTB 2.0 first in some way, then use this script to extract paragraphs from the dataset. Just put the script "documents_all_rels.py" and the folder “PDTB 2.0” under the same path, then run this script to get "train_docs_all_rels/valid_docs_all_rels/test_docs_all_rels".

This worked, thank you so much!
